language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_install:
- npm install react-addons-test-utils
addons:
  code_climate:
    repo_token: b9ee922e13fa2b797410c16993ecaf91fe076ad0d12ce4d191ae92b1c1669a01
